* Emulate the graph on p.2 of the mockup pdf.
** *???* If boxes are too small to fit a number, aggregate somehow.
** DONE Stack the boxes, with a line and no space between.
** Write the total above each stack.
** Color the boxes per Manuela's specs.
** DONE Put text indicating the amount on each box.
"By default, [the x and y arguments to matplotlib.axes.Axes.text() are] in data coordinates."
https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.axes.Axes.text.html
** DONE No y-axis. Years on the x-axis.
** DONE Big space between each column.
** Change fonts
refer to fonts/custom-font.py for
*** color: white
*** style: Montserrat black & Montserrat light
source: https://fonts.google.com/specimen/Montserrat
** Include text from an accompanying .txt file.
* TODO build a pdf
** TODO use matplotlib
** DONE reportlab is too complex and unfree
pip3 install reportlab
*** DONE ReportLab
https://www.reportlab.com/documentation/
*** custom fonts in reportlab
https://www.reportlab.com/documentation/faq/#2.6.2
** DONE pyfpdf appears to badly support Python 3
pip install --upgrade pip # afte running this, did not have pip3
seems to be working: "python3 -m pip install fpdf"
recommended was      "python  -m pip install fpdf"
