* ONGOING update docker image
** TODO in Dockerfile, update pandas, conda, jupyter script
*** update Jupyter server script
The IP address should be 0.0.0.0:
/opt/conda/bin/jupyter notebook --notebook-dir=/mnt --ip='0.0.0.0' --port=8887 --no-browser --allow-root

And then, in browser, maybe just connect to http://127.0.0.1:8887/tree
(the giant URL shown at the bottom of the output definitely works, but needs some editing -- choose one of the two things in parens, and then delete the parens).
*** updating conda updates pandas also
"conda update --prefix /opt/conda anaconda --yes"
** install a pdf library
*** get pip3
apt install python3-pip -y # seemed to work; now pip3 is installed
pip3 install --upgrade pip # reported was already up to date
*** reportlab looks good
pip3 install reportlab
*** DONE pyfpdf appears to badly support Python 3
pip install --upgrade pip # afte running this, did not have pip3
seems to be working: "python3 -m pip install fpdf"
recommended was      "python  -m pip install fpdf"
* ReportLab
https://www.reportlab.com/documentation/
**** custom fonts in reportlab
https://www.reportlab.com/documentation/faq/#2.6.2
* Emulate the graph on p.2 of the mockup pdf.
** *???* If boxes are too small to fit a number, aggregate somehow.
** DONE Stack the boxes, with a line and no space between.
** Color the boxes per Manuela's specs.
** DONE Put text indicating the amount on each box.
"By default, [the x and y arguments to matplotlib.axes.Axes.text() are] in data coordinates."
https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.axes.Axes.text.html
** DONE No y-axis. Years on the x-axis.
** DONE Big space between each column.
** Change fonts
refer to fonts/custom-font.py for
*** color: white
*** style: Montserrat black & Montserrat light
source: https://fonts.google.com/specimen/Montserrat
** Include text from an accompanying .txt file.
** TODO build a pdf
